# Generated by Django 3.1.14 on 2024-04-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpmninstance',
            old_name='chaincode_contend',
            new_name='chaincode_content',
        ),
        migrations.RemoveField(
            model_name='bpmn',
            name='chaincode',
        ),
        migrations.RemoveField(
            model_name='bpmn',
            name='ffiContent',
        ),
        migrations.RemoveField(
            model_name='bpmn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bpmninstance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bpmninstance',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bpmninstance',
            name='ffiContent',
            field=models.TextField(blank=True, default=None, help_text='content of ffi file', null=True),
        ),
        migrations.AddField(
            model_name='loleidoorgjoinconsortiuminvitation',
            name='invitor',
            field=models.ForeignKey(default=None, help_text='related loleido_organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='sended_invitations', to='api.loleidoorganization'),
        ),
        migrations.AddField(
            model_name='userjoinorginvitation',
            name='invitor',
            field=models.ForeignKey(default=None, help_text='related user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sended_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-640015a809cf415aa89194572ae36d3b', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='bpmninstance',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Fullfilled', 'Fullfilled'), ('Generated', 'Generated'), ('Installed', 'Installed'), ('Registered', 'Registered')], default='pending', help_text='status of BPMNInstance', max_length=32),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-7dd86cc8da64488584878d58bcc9ceeb', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
