# Generated by Django 3.1.14 on 2024-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240409_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-0743d5b1f6ff4d0380fd9e62c4f38f34', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-4e0edfea4cd4483cbeacdd35bfbaafea', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
