# Generated by Django 3.1.14 on 2024-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240418_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-d74c0d1f5c9749478afa86c242c1912e', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-c968946a1f524c5f810da4fd9fe95200', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
